theme: jekyll-theme-leap-day
title: Result Library BOM
description: Bill of Materials for Result libraries
current_version: 0.3.2.0
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
